source 'https://rubygems.org'

gem 'pry', '~> 0.9.12'
gem 'pry-rails', '0.3.2'
gem 'pry-coolline', '~> 0.2.2'
gem 'pry-doc', '~> 0.4.6'
gem 'hirb', '~> 0.7.1'
gem 'interactive_editor'
gem 'fancy_irb', '0.7.3'
gem 'awesome_print', '~> 1.1.0'
gem 'veewee', :git => 'https://github.com/jedi4ever/veewee'
