source 'https://rubygems.org'

gem 'pry'
gem 'pry-coolline'
gem 'pry-doc'
gem 'hirb'
gem 'interactive_editor'
gem 'fancy_irb'
gem 'awesome_print'
gem 'hub'
gem 'veewee', git: 'https://github.com/jedi4ever/veewee'
